version: '2'
services:
  transaction-processor:
    image: transaction-processor
    container_name: transaction-processor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
